//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int IDuser { get; set; }
        public bool UserType { get; set; }
        public int PasgoRID { get; set; }
        public int Num { get; set; }
        public System.DateTime CallTime { get; set; }
        public System.DateTime ETA { get; set; }
        public Nullable<System.DateTime> ArriveTime { get; set; }
        public string Request { get; set; }
        public int Status { get; set; }
    
        public virtual PasgoRestaurant PasgoRestaurant { get; set; }
    }
}
