//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhamPhaBv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhamPhaBv()
        {
            this.KhamPhas = new HashSet<KhamPha>();
        }
    
        public int IdBv { get; set; }
        public string Img { get; set; }
        public Nullable<int> Diadiem { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Promotion { get; set; }
        public string Name { get; set; }
        public string LinkBv { get; set; }
        public Nullable<int> City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhamPha> KhamPhas { get; set; }
    }
}
