//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PasGoEntities : DbContext
    {
        public PasGoEntities()
            : base("name=PasGoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnUong> AnUongs { get; set; }
        public virtual DbSet<BaiViet> BaiViets { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ConnectionIdDB> ConnectionIdDBs { get; set; }
        public virtual DbSet<Conversation> Conversations { get; set; }
        public virtual DbSet<HeaderSlide> HeaderSlides { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<img> imgs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhamPha> KhamPhas { get; set; }
        public virtual DbSet<KhamPhaBv> KhamPhaBvs { get; set; }
        public virtual DbSet<khuyenmai> khuyenmais { get; set; }
        public virtual DbSet<loc> locs { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MoiNhat> MoiNhats { get; set; }
        public virtual DbSet<NhaHangUyTin> NhaHangUyTins { get; set; }
        public virtual DbSet<PasgoRestaurant> PasgoRestaurants { get; set; }
        public virtual DbSet<PasgoTV> PasgoTVs { get; set; }
        public virtual DbSet<PasgoUser> PasgoUsers { get; set; }
        public virtual DbSet<PasgoVisitor> PasgoVisitors { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<ThuongHieuChuoi> ThuongHieuChuois { get; set; }
        public virtual DbSet<ThuongHieuChuoiD> ThuongHieuChuoiDS { get; set; }
        public virtual DbSet<UuDaiHot> UuDaiHots { get; set; }
        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<thongtinthem> thongtinthems { get; set; }
    
        public virtual ObjectResult<AddConnectionId_Result> AddConnectionId(string phonenumber, string connection)
        {
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var connectionParameter = connection != null ?
                new ObjectParameter("connection", connection) :
                new ObjectParameter("connection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AddConnectionId_Result>("AddConnectionId", phonenumberParameter, connectionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AddConversation(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AddConversation", useridParameter);
        }
    
        public virtual ObjectResult<allImg_Result> allImg(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<allImg_Result>("allImg", idParameter);
        }
    
        public virtual ObjectResult<AnUong2SP_Result> AnUong2SP(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AnUong2SP_Result>("AnUong2SP", cityParameter);
        }
    
        public virtual ObjectResult<AnUongSP_Result> AnUongSP(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AnUongSP_Result>("AnUongSP", cityParameter);
        }
    
        public virtual ObjectResult<APIsearch_Result> APIsearch(Nullable<int> city, Nullable<int> type, string keyword)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APIsearch_Result>("APIsearch", cityParameter, typeParameter, keywordParameter);
        }
    
        public virtual ObjectResult<BaiVietSP_Result> BaiVietSP(Nullable<int> city, Nullable<int> type)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BaiVietSP_Result>("BaiVietSP", cityParameter, typeParameter);
        }
    
        public virtual ObjectResult<ChatHistory_Result> ChatHistory(Nullable<int> conversationid)
        {
            var conversationidParameter = conversationid.HasValue ?
                new ObjectParameter("conversationid", conversationid) :
                new ObjectParameter("conversationid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChatHistory_Result>("ChatHistory", conversationidParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckUser(string phone)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckUser", phoneParameter);
        }
    
        public virtual ObjectResult<ThuongHieuChuoi> ChuoiThuongHieuSP(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThuongHieuChuoi>("ChuoiThuongHieuSP", cityParameter);
        }
    
        public virtual ObjectResult<ThuongHieuChuoi> ChuoiThuongHieuSP(Nullable<int> city, MergeOption mergeOption)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThuongHieuChuoi>("ChuoiThuongHieuSP", mergeOption, cityParameter);
        }
    
        public virtual int DeleteConnection(string connection)
        {
            var connectionParameter = connection != null ?
                new ObjectParameter("connection", connection) :
                new ObjectParameter("connection", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteConnection", connectionParameter);
        }
    
        public virtual ObjectResult<DoiTacSP_Result> DoiTacSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoiTacSP_Result>("DoiTacSP");
        }
    
        public virtual ObjectResult<FindConnectionID_Result> FindConnectionID(Nullable<int> idconversation)
        {
            var idconversationParameter = idconversation.HasValue ?
                new ObjectParameter("idconversation", idconversation) :
                new ObjectParameter("idconversation", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindConnectionID_Result>("FindConnectionID", idconversationParameter);
        }
    
        public virtual ObjectResult<FullInfoHistory_Result> FullInfoHistory(Nullable<int> id, Nullable<int> type, Nullable<System.DateTime> from, Nullable<System.DateTime> to)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FullInfoHistory_Result>("FullInfoHistory", idParameter, typeParameter, fromParameter, toParameter);
        }
    
        public virtual ObjectResult<PasgoRestaurant> FullInfoRestaurant(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PasgoRestaurant>("FullInfoRestaurant", idParameter);
        }
    
        public virtual ObjectResult<PasgoRestaurant> FullInfoRestaurant(Nullable<int> id, MergeOption mergeOption)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PasgoRestaurant>("FullInfoRestaurant", mergeOption, idParameter);
        }
    
        public virtual ObjectResult<FullInfoUser_Result> FullInfoUser(Nullable<int> id, Nullable<bool> type)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FullInfoUser_Result>("FullInfoUser", idParameter, typeParameter);
        }
    
        public virtual ObjectResult<getAllConn_Result> getAllConn(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllConn_Result>("getAllConn", idParameter);
        }
    
        public virtual ObjectResult<GetConversation_Result> GetConversation(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetConversation_Result>("GetConversation", idParameter);
        }
    
        public virtual ObjectResult<GetConversationList_Result> GetConversationList(Nullable<int> id, Nullable<int> type)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetConversationList_Result>("GetConversationList", idParameter, typeParameter);
        }
    
        public virtual ObjectResult<GetUserInforSP_Result> GetUserInforSP(string phone)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserInforSP_Result>("GetUserInforSP", phoneParameter);
        }
    
        public virtual ObjectResult<imgSlide_Result> imgSlide()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<imgSlide_Result>("imgSlide");
        }
    
        public virtual ObjectResult<Nullable<int>> InsertUser(string name, string phoneNumber, string email, Nullable<bool> gender, string salt, string passwordHashed)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(bool));
    
            var saltParameter = salt != null ?
                new ObjectParameter("Salt", salt) :
                new ObjectParameter("Salt", typeof(string));
    
            var passwordHashedParameter = passwordHashed != null ?
                new ObjectParameter("PasswordHashed", passwordHashed) :
                new ObjectParameter("PasswordHashed", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("InsertUser", nameParameter, phoneNumberParameter, emailParameter, genderParameter, saltParameter, passwordHashedParameter);
        }
    
        public virtual ObjectResult<KhachHang> KhachhangSP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("KhachhangSP");
        }
    
        public virtual ObjectResult<KhachHang> KhachhangSP(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhachHang>("KhachhangSP", mergeOption);
        }
    
        public virtual ObjectResult<KhamPhaBv> KhamPhaSP(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhamPhaBv>("KhamPhaSP", cityParameter);
        }
    
        public virtual ObjectResult<KhamPhaBv> KhamPhaSP(Nullable<int> city, MergeOption mergeOption)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhamPhaBv>("KhamPhaSP", mergeOption, cityParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LockUnlock(Nullable<int> pasgoid, Nullable<int> loai, string type, Nullable<int> howlong)
        {
            var pasgoidParameter = pasgoid.HasValue ?
                new ObjectParameter("pasgoid", pasgoid) :
                new ObjectParameter("pasgoid", typeof(int));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(int));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var howlongParameter = howlong.HasValue ?
                new ObjectParameter("howlong", howlong) :
                new ObjectParameter("howlong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LockUnlock", pasgoidParameter, loaiParameter, typeParameter, howlongParameter);
        }
    
        public virtual ObjectResult<Login_Result> Login(string phone, string hash)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var hashParameter = hash != null ?
                new ObjectParameter("hash", hash) :
                new ObjectParameter("hash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Login_Result>("Login", phoneParameter, hashParameter);
        }
    
        public virtual ObjectResult<Menu> MenuCatalogue(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Menu>("MenuCatalogue", cityParameter);
        }
    
        public virtual ObjectResult<Menu> MenuCatalogue(Nullable<int> city, MergeOption mergeOption)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Menu>("MenuCatalogue", mergeOption, cityParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> ModifyConnectionId(Nullable<int> id, string connection, Nullable<int> type)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var connectionParameter = connection != null ?
                new ObjectParameter("connection", connection) :
                new ObjectParameter("connection", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ModifyConnectionId", idParameter, connectionParameter, typeParameter);
        }
    
        public virtual ObjectResult<MoiNhatSP_Result> MoiNhatSP(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MoiNhatSP_Result>("MoiNhatSP", cityParameter);
        }
    
        public virtual int NewMessage(Nullable<int> idconversation, Nullable<int> idreceived, Nullable<int> type)
        {
            var idconversationParameter = idconversation.HasValue ?
                new ObjectParameter("idconversation", idconversation) :
                new ObjectParameter("idconversation", typeof(int));
    
            var idreceivedParameter = idreceived.HasValue ?
                new ObjectParameter("idreceived", idreceived) :
                new ObjectParameter("idreceived", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NewMessage", idconversationParameter, idreceivedParameter, typeParameter);
        }
    
        public virtual ObjectResult<PasgoTV> PasgotvSP(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PasgoTV>("PasgotvSP", cityParameter);
        }
    
        public virtual ObjectResult<PasgoTV> PasgotvSP(Nullable<int> city, MergeOption mergeOption)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PasgoTV>("PasgotvSP", mergeOption, cityParameter);
        }
    
        public virtual ObjectResult<string> Salt(string sdt)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Salt", sdtParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SaveMessage(Nullable<int> id, Nullable<bool> messagetype, string message)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var messagetypeParameter = messagetype.HasValue ?
                new ObjectParameter("messagetype", messagetype) :
                new ObjectParameter("messagetype", typeof(bool));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SaveMessage", idParameter, messagetypeParameter, messageParameter);
        }
    
        public virtual ObjectResult<ThuocThuongHieuChuoi_Result> SearchChuoi(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThuocThuongHieuChuoi_Result>("SearchChuoi", nameParameter);
        }
    
        public virtual ObjectResult<SimpleHistory_Result> SimpleHistory(Nullable<int> id, Nullable<bool> type)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SimpleHistory_Result>("SimpleHistory", idParameter, typeParameter);
        }
    
        public virtual ObjectResult<SimpleRestaurant_Result> SimpleRestaurant(Nullable<int> city, Nullable<int> promotion, Nullable<int> number, string name)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            var promotionParameter = promotion.HasValue ?
                new ObjectParameter("promotion", promotion) :
                new ObjectParameter("promotion", typeof(int));
    
            var numberParameter = number.HasValue ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SimpleRestaurant_Result>("SimpleRestaurant", cityParameter, promotionParameter, numberParameter, nameParameter);
        }
    
        public virtual ObjectResult<SimpleUser_Result> SimpleUser(string id, string phone, string email, string name, Nullable<bool> @lock, Nullable<bool> visitor)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("lock", @lock) :
                new ObjectParameter("lock", typeof(bool));
    
            var visitorParameter = visitor.HasValue ?
                new ObjectParameter("visitor", visitor) :
                new ObjectParameter("visitor", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SimpleUser_Result>("SimpleUser", idParameter, phoneParameter, emailParameter, nameParameter, lockParameter, visitorParameter);
        }
    
        public virtual ObjectResult<StaffList_Result> StaffList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StaffList_Result>("StaffList");
        }
    
        public virtual ObjectResult<StaffList_Result> StaffSearch(string phone, string name, Nullable<int> level)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<StaffList_Result>("StaffSearch", phoneParameter, nameParameter, levelParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> StaffSetLevels(string phone, Nullable<int> level)
        {
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var levelParameter = level.HasValue ?
                new ObjectParameter("level", level) :
                new ObjectParameter("level", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("StaffSetLevels", phoneParameter, levelParameter);
        }
    
        public virtual ObjectResult<test1_Result> test1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<test1_Result>("test1", idParameter);
        }
    
        public virtual ObjectResult<thongtinthemSP_Result> thongtinthemSP(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongtinthemSP_Result>("thongtinthemSP", idParameter);
        }
    
        public virtual ObjectResult<ThuocThuongHieuChuoi_Result> ThuocThuongHieuChuoi(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThuocThuongHieuChuoi_Result>("ThuocThuongHieuChuoi", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateAccount(Nullable<int> id, string name, string phonenumber, string email, Nullable<System.DateTime> dob, Nullable<bool> gender)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phonenumberParameter = phonenumber != null ?
                new ObjectParameter("phonenumber", phonenumber) :
                new ObjectParameter("phonenumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateAccount", idParameter, nameParameter, phonenumberParameter, emailParameter, dobParameter, genderParameter);
        }
    
        public virtual int UpdateChuoi(Nullable<int> nhahang, Nullable<int> chuoicu, Nullable<int> chuoimoi, Nullable<int> mucdich)
        {
            var nhahangParameter = nhahang.HasValue ?
                new ObjectParameter("nhahang", nhahang) :
                new ObjectParameter("nhahang", typeof(int));
    
            var chuoicuParameter = chuoicu.HasValue ?
                new ObjectParameter("chuoicu", chuoicu) :
                new ObjectParameter("chuoicu", typeof(int));
    
            var chuoimoiParameter = chuoimoi.HasValue ?
                new ObjectParameter("chuoimoi", chuoimoi) :
                new ObjectParameter("chuoimoi", typeof(int));
    
            var mucdichParameter = mucdich.HasValue ?
                new ObjectParameter("mucdich", mucdich) :
                new ObjectParameter("mucdich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateChuoi", nhahangParameter, chuoicuParameter, chuoimoiParameter, mucdichParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateConversationStatus(Nullable<int> idconversation, Nullable<bool> status)
        {
            var idconversationParameter = idconversation.HasValue ?
                new ObjectParameter("idconversation", idconversation) :
                new ObjectParameter("idconversation", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateConversationStatus", idconversationParameter, statusParameter);
        }
    
        public virtual int UpdateIMG(Nullable<int> id, string link, string mota, Nullable<int> loai, Nullable<int> nhahang, Nullable<int> mucdich)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var linkParameter = link != null ?
                new ObjectParameter("link", link) :
                new ObjectParameter("link", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(int));
    
            var nhahangParameter = nhahang.HasValue ?
                new ObjectParameter("nhahang", nhahang) :
                new ObjectParameter("nhahang", typeof(int));
    
            var mucdichParameter = mucdich.HasValue ?
                new ObjectParameter("mucdich", mucdich) :
                new ObjectParameter("mucdich", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateIMG", idParameter, linkParameter, motaParameter, loaiParameter, nhahangParameter, mucdichParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateInsertImg(Nullable<int> id, string link, string mota, Nullable<int> type, Nullable<int> nhahangid, Nullable<int> loai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var linkParameter = link != null ?
                new ObjectParameter("link", link) :
                new ObjectParameter("link", typeof(string));
    
            var motaParameter = mota != null ?
                new ObjectParameter("mota", mota) :
                new ObjectParameter("mota", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            var nhahangidParameter = nhahangid.HasValue ?
                new ObjectParameter("nhahangid", nhahangid) :
                new ObjectParameter("nhahangid", typeof(int));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateInsertImg", idParameter, linkParameter, motaParameter, typeParameter, nhahangidParameter, loaiParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateInsertRestaurantInfo(Nullable<int> id, string name, string link, string promotion, Nullable<int> star, Nullable<int> dollar, string address, Nullable<int> city, Nullable<int> percent, string feature, string loaihinh, string phuphop, string khonggian, string chodexe, string dactrung, string thongtinthem, string gioithieu, Nullable<int> loai)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var linkParameter = link != null ?
                new ObjectParameter("link", link) :
                new ObjectParameter("link", typeof(string));
    
            var promotionParameter = promotion != null ?
                new ObjectParameter("promotion", promotion) :
                new ObjectParameter("promotion", typeof(string));
    
            var starParameter = star.HasValue ?
                new ObjectParameter("star", star) :
                new ObjectParameter("star", typeof(int));
    
            var dollarParameter = dollar.HasValue ?
                new ObjectParameter("dollar", dollar) :
                new ObjectParameter("dollar", typeof(int));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            var percentParameter = percent.HasValue ?
                new ObjectParameter("percent", percent) :
                new ObjectParameter("percent", typeof(int));
    
            var featureParameter = feature != null ?
                new ObjectParameter("feature", feature) :
                new ObjectParameter("feature", typeof(string));
    
            var loaihinhParameter = loaihinh != null ?
                new ObjectParameter("loaihinh", loaihinh) :
                new ObjectParameter("loaihinh", typeof(string));
    
            var phuphopParameter = phuphop != null ?
                new ObjectParameter("phuphop", phuphop) :
                new ObjectParameter("phuphop", typeof(string));
    
            var khonggianParameter = khonggian != null ?
                new ObjectParameter("khonggian", khonggian) :
                new ObjectParameter("khonggian", typeof(string));
    
            var chodexeParameter = chodexe != null ?
                new ObjectParameter("chodexe", chodexe) :
                new ObjectParameter("chodexe", typeof(string));
    
            var dactrungParameter = dactrung != null ?
                new ObjectParameter("dactrung", dactrung) :
                new ObjectParameter("dactrung", typeof(string));
    
            var thongtinthemParameter = thongtinthem != null ?
                new ObjectParameter("thongtinthem", thongtinthem) :
                new ObjectParameter("thongtinthem", typeof(string));
    
            var gioithieuParameter = gioithieu != null ?
                new ObjectParameter("gioithieu", gioithieu) :
                new ObjectParameter("gioithieu", typeof(string));
    
            var loaiParameter = loai.HasValue ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateInsertRestaurantInfo", idParameter, nameParameter, linkParameter, promotionParameter, starParameter, dollarParameter, addressParameter, cityParameter, percentParameter, featureParameter, loaihinhParameter, phuphopParameter, khonggianParameter, chodexeParameter, dactrungParameter, thongtinthemParameter, gioithieuParameter, loaiParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdatePassword(Nullable<int> id, string oldhash, string newsalt, string newhash)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var oldhashParameter = oldhash != null ?
                new ObjectParameter("oldhash", oldhash) :
                new ObjectParameter("oldhash", typeof(string));
    
            var newsaltParameter = newsalt != null ?
                new ObjectParameter("newsalt", newsalt) :
                new ObjectParameter("newsalt", typeof(string));
    
            var newhashParameter = newhash != null ?
                new ObjectParameter("newhash", newhash) :
                new ObjectParameter("newhash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdatePassword", idParameter, oldhashParameter, newsaltParameter, newhashParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateThongtinthem(Nullable<int> id, Nullable<bool> pr, Nullable<bool> tre, Nullable<bool> ht, Nullable<bool> wf, Nullable<bool> dh, Nullable<bool> visa, Nullable<bool> mc, Nullable<bool> vat, Nullable<bool> cho, Nullable<bool> hd, Nullable<bool> ban, Nullable<bool> ship, Nullable<bool> kara, Nullable<bool> sk)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var prParameter = pr.HasValue ?
                new ObjectParameter("pr", pr) :
                new ObjectParameter("pr", typeof(bool));
    
            var treParameter = tre.HasValue ?
                new ObjectParameter("tre", tre) :
                new ObjectParameter("tre", typeof(bool));
    
            var htParameter = ht.HasValue ?
                new ObjectParameter("ht", ht) :
                new ObjectParameter("ht", typeof(bool));
    
            var wfParameter = wf.HasValue ?
                new ObjectParameter("wf", wf) :
                new ObjectParameter("wf", typeof(bool));
    
            var dhParameter = dh.HasValue ?
                new ObjectParameter("dh", dh) :
                new ObjectParameter("dh", typeof(bool));
    
            var visaParameter = visa.HasValue ?
                new ObjectParameter("visa", visa) :
                new ObjectParameter("visa", typeof(bool));
    
            var mcParameter = mc.HasValue ?
                new ObjectParameter("mc", mc) :
                new ObjectParameter("mc", typeof(bool));
    
            var vatParameter = vat.HasValue ?
                new ObjectParameter("vat", vat) :
                new ObjectParameter("vat", typeof(bool));
    
            var choParameter = cho.HasValue ?
                new ObjectParameter("cho", cho) :
                new ObjectParameter("cho", typeof(bool));
    
            var hdParameter = hd.HasValue ?
                new ObjectParameter("hd", hd) :
                new ObjectParameter("hd", typeof(bool));
    
            var banParameter = ban.HasValue ?
                new ObjectParameter("ban", ban) :
                new ObjectParameter("ban", typeof(bool));
    
            var shipParameter = ship.HasValue ?
                new ObjectParameter("ship", ship) :
                new ObjectParameter("ship", typeof(bool));
    
            var karaParameter = kara.HasValue ?
                new ObjectParameter("kara", kara) :
                new ObjectParameter("kara", typeof(bool));
    
            var skParameter = sk.HasValue ?
                new ObjectParameter("sk", sk) :
                new ObjectParameter("sk", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateThongtinthem", idParameter, prParameter, treParameter, htParameter, wfParameter, dhParameter, visaParameter, mcParameter, vatParameter, choParameter, hdParameter, banParameter, shipParameter, karaParameter, skParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateUserInfo(Nullable<int> id, string name, string email, Nullable<System.DateTime> dob, Nullable<bool> gender)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateUserInfo", idParameter, nameParameter, emailParameter, dobParameter, genderParameter);
        }
    
        public virtual ObjectResult<UuDaiSP_Result> UuDaiSP(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UuDaiSP_Result>("UuDaiSP", cityParameter);
        }
    
        public virtual ObjectResult<AnUongSP_Result> UyTinSP(Nullable<int> city)
        {
            var cityParameter = city.HasValue ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AnUongSP_Result>("UyTinSP", cityParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateAvatar(Nullable<int> id, string avatarid)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var avataridParameter = avatarid != null ?
                new ObjectParameter("avatarid", avatarid) :
                new ObjectParameter("avatarid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateAvatar", idParameter, avataridParameter);
        }
    }
}
