//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasgoRestaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PasgoRestaurant()
        {
            this.AnUongs = new HashSet<AnUong>();
            this.HeaderSlides = new HashSet<HeaderSlide>();
            this.imgs = new HashSet<img>();
            this.KhamPhas = new HashSet<KhamPha>();
            this.khuyenmais = new HashSet<khuyenmai>();
            this.MoiNhats = new HashSet<MoiNhat>();
            this.NhaHangUyTins = new HashSet<NhaHangUyTin>();
            this.thongtinthems = new HashSet<thongtinthem>();
            this.UuDaiHots = new HashSet<UuDaiHot>();
            this.ThuongHieuChuoiDS = new HashSet<ThuongHieuChuoiD>();
            this.Histories = new HashSet<History>();
        }
    
        public int PasgoRID { get; set; }
        public string RName { get; set; }
        public string Rlink { get; set; }
        public string Rpromotion { get; set; }
        public int Rstar { get; set; }
        public int Rdollar { get; set; }
        public string Raddress { get; set; }
        public int Rcity { get; set; }
        public string RLoaiHinh { get; set; }
        public string RPhuHop { get; set; }
        public string RKhongGian { get; set; }
        public string RChoDeXe { get; set; }
        public string RDacTrung { get; set; }
        public string RThongTinThem { get; set; }
        public string RGioiThieu { get; set; }
        public Nullable<System.DateTime> Rdate { get; set; }
        public int RpromotionPercent { get; set; }
        public string Rfeature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnUong> AnUongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HeaderSlide> HeaderSlides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<img> imgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhamPha> KhamPhas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<khuyenmai> khuyenmais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoiNhat> MoiNhats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhaHangUyTin> NhaHangUyTins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thongtinthem> thongtinthems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UuDaiHot> UuDaiHots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuongHieuChuoiD> ThuongHieuChuoiDS { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
    }
}
