//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinthem
    {
        public int Id { get; set; }
        public bool PhongRieng { get; set; }
        public bool GheTreEm { get; set; }
        public bool HutThuoc { get; set; }
        public bool Wifi { get; set; }
        public bool DieuHoa { get; set; }
        public bool Visa { get; set; }
        public bool MayChieu { get; set; }
        public bool VAT { get; set; }
        public bool ChoChoi { get; set; }
        public bool HDtructiep { get; set; }
        public bool NgoaiTroi { get; set; }
        public bool ShipPasgo { get; set; }
        public bool Karaoke { get; set; }
        public bool SuKien { get; set; }
    
        public virtual PasgoRestaurant PasgoRestaurant { get; set; }
    }
}
