//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuongHieuChuoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuongHieuChuoi()
        {
            this.ThuongHieuChuoiDS = new HashSet<ThuongHieuChuoiD>();
        }
    
        public int IdThuongHieu { get; set; }
        public string Name { get; set; }
        public string Promotion { get; set; }
        public string LinkTH { get; set; }
        public string ImgTH { get; set; }
        public Nullable<int> City { get; set; }
        public string NameDT { get; set; }
        public string AddressDT { get; set; }
        public string ImgDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuongHieuChuoiD> ThuongHieuChuoiDS { get; set; }
    }
}
